# -*- coding: utf-8 -*-
"""Copy of Capstone Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VM0zOjCFkEg79RC0IF4as2Unm6X1QvDG

# Capstone Project
## Neural translation model
### Instructions

In this notebook, you will create a neural network that translates from English to German. You will use concepts from throughout this course, including building more flexible model architectures, freezing layers, data processing pipeline and sequence modelling.

This project is peer-assessed. Within this notebook you will find instructions in each section for how to complete the project. Pay close attention to the instructions as the peer review will be carried out according to a grading rubric that checks key parts of the project instructions. Feel free to add extra cells into the notebook as required.

### How to submit

When you have completed the Capstone project notebook, you will submit a pdf of the notebook for peer review. First ensure that the notebook has been fully executed from beginning to end, and all of the cell outputs are visible. This is important, as the grading rubric depends on the reviewer being able to view the outputs of your notebook. Save the notebook as a pdf (you could download the notebook with File -> Download .ipynb, open the notebook locally, and then File -> Download as -> PDF via LaTeX), and then submit this pdf for review.

### Let's get started!

We'll start by running some imports, and loading the dataset. For this project you are free to make further imports throughout the notebook as you wish.
"""

import tensorflow as tf
import tensorflow_hub as hub
import unicodedata
import re
from IPython.display import Image

"""For the capstone project, you will use a language dataset from http://www.manythings.org/anki/ to build a neural translation model. This dataset consists of over 200,000 pairs of sentences in English and German. In order to make the training quicker, we will restrict to our dataset to 20,000 pairs. Feel free to change this if you wish - the size of the dataset used is not part of the grading rubric.

Your goal is to develop a neural translation model from English to German, making use of a pre-trained English word embedding module.

#### Import the data

The dataset is available for download as a zip file at the following link:

https://drive.google.com/open?id=1KczOciG7sYY7SB9UlBeRP1T9659b121Q

You should store the unzipped folder in Drive for use in this Colab notebook.
"""

# Run this cell to connect to your Drive folder

from google.colab import drive
drive.mount('/content/gdrive')

# Run this cell to load the dataset

NUM_EXAMPLES = 20000
data_examples = []
with open('gdrive/MyDrive/data/deu.txt', 'r', encoding='utf8') as f:
    for line in f.readlines():
        if len(data_examples) < NUM_EXAMPLES:
            data_examples.append(line)
        else:
            break

print(data_examples[5])

# These functions preprocess English and German sentences

def unicode_to_ascii(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')

def preprocess_sentence(sentence):
    sentence = sentence.lower().strip()
    sentence = re.sub(r"ü", 'ue', sentence)
    sentence = re.sub(r"ä", 'ae', sentence)
    sentence = re.sub(r"ö", 'oe', sentence)
    sentence = re.sub(r'ß', 'ss', sentence)
    
    sentence = unicode_to_ascii(sentence)
    sentence = re.sub(r"([?.!,])", r" \1 ", sentence)
    sentence = re.sub(r"[^a-z?.!,']+", " ", sentence)
    sentence = re.sub(r'[" "]+', " ", sentence)
    
    return sentence.strip()

"""#### The custom translation model
The following is a schematic of the custom translation model architecture you will develop in this project.
"""



# Run this cell to download and view a schematic diagram for the neural translation model

!wget -q -O neural_translation_model.png --no-check-certificate "https://docs.google.com/uc?export=download&id=1XsS1VlXoaEo-RbYNilJ9jcscNZvsSPmd"
Image("neural_translation_model.png")

"""The custom model consists of an encoder RNN and a decoder RNN. The encoder takes words of an English sentence as input, and uses a pre-trained word embedding to embed the words into a 128-dimensional space. To indicate the end of the input sentence, a special end token (in the same 128-dimensional space) is passed in as an input. This token is a TensorFlow Variable that is learned in the training phase (unlike the pre-trained word embedding, which is frozen).

The decoder RNN takes the internal state of the encoder network as its initial state. A start token is passed in as the first input, which is embedded using a learned German word embedding. The decoder RNN then makes a prediction for the next German word, which during inference is then passed in as the following input, and this process is repeated until the special `<end>` token is emitted from the decoder.

## 1. Text preprocessing
* Create separate lists of English and German sentences, and preprocess them using the `preprocess_sentence` function provided for you above.
* Add a special `"<start>"` and `"<end>"` token to the beginning and end of every German sentence.
* Use the Tokenizer class from the `tf.keras.preprocessing.text` module to tokenize the German sentences, ensuring that no character filters are applied. _Hint: use the Tokenizer's "filter" keyword argument._
* Print out at least 5 randomly chosen examples of (preprocessed) English and German sentence pairs. For the German sentence, print out the text (with start and end tokens) as well as the tokenized sequence.
* Pad the end of the tokenized German sequences with zeros, and batch the complete set of sequences into one numpy array.
"""

indice = [i for i in range(len(data_examples[100])) if data_examples[100][i]=="!" or data_examples[100][i]=="."]
print(indice)
print(data_examples[100][0:indice[0]],data_examples[100][indice[0]+2:indice[1]])

def eng_germ(data_examples):
  eng=[]
  germ=[]
  for x in data_examples:
    indices = [i for i in range(len(x)) if x[i]=="!" or x[i]=="?" or x[i]=="."]
    eng.append(x[0:indices[0]])
    germ.append(x[indices[0]+2:indices[1]])
  return (eng,germ)

eng,germ = eng_germ(data_examples)

print(eng[100])
eng=[unicode_to_ascii(i) for i in [m for m in eng]]
germ=[unicode_to_ascii(i) for i in [m for m in germ]]
print(eng[100])
eng =[preprocess_sentence(x) for x in eng]
germ=[preprocess_sentence(x) for x in germ]
print(eng[100])

#eng1=["<start>"+x+"<end>" for x in eng]
germ1=["<start> "+x+" <end>" for x in germ]

token=tf.keras.preprocessing.text.Tokenizer(
    num_words=None,
    
    oov_token="UNK",
    char_level=False,
    document_count=0,
    filters="",
    

)

token.fit_on_texts(germ1)

config =token.get_config()
print(config.keys())
import json
word_index =json.loads(config["word_index"])

m=100
list1=token.texts_to_sequences(germ1[m:m+5])
print(len(list1))

for i in range(5):
  print(f"German: {germ1[i+m]} German sequence: {list1[i]} English: {eng[i+m]}")

germ_final = tf.keras.preprocessing.sequence.pad_sequences(token.texts_to_sequences(germ1),maxlen=44,padding="post",truncating="pre")

print(germ_final.shape)

"""## 2. Prepare the data

#### Load the embedding layer
As part of the dataset preproceessing for this project, you will use a pre-trained English word embedding module from TensorFlow Hub. The URL for the module is https://tfhub.dev/google/tf2-preview/nnlm-en-dim128-with-normalization/1.

This embedding takes a batch of text tokens in a 1-D tensor of strings as input. It then embeds the separate tokens into a 128-dimensional space. 

The code to load and test the embedding layer is provided for you below.

**NB:** this model can also be used as a sentence embedding module. The module will process each token by removing punctuation and splitting on spaces. It then averages the word embeddings over a sentence to give a single embedding vector. However, we will use it only as a word embedding module, and will pass each word in the input sentence as a separate token.
"""

# Load embedding module from Tensorflow Hub

embedding_layer = hub.KerasLayer("https://tfhub.dev/google/tf2-preview/nnlm-en-dim128/1", 
                                 output_shape=[128], input_shape=[], dtype=tf.string)

# Test the layer

embedding_layer(tf.constant(["these", "aren't", "the", "droids", "you're", "looking", "for"])).shape

"""You should now prepare the training and validation Datasets.

* Create a random training and validation set split of the data, reserving e.g. 20% of the data for validation (NB: each English dataset example is a single sentence string, and each German dataset example is a sequence of padded integer tokens).
* Load the training and validation sets into a tf.data.Dataset object, passing in a tuple of English and German data for both training and validation sets.
* Create a function to map over the datasets that splits each English sentence at spaces. Apply this function to both Dataset objects using the map method. _Hint: look at the tf.strings.split function._
* Create a function to map over the datasets that embeds each sequence of English words using the loaded embedding layer/model. Apply this function to both Dataset objects using the map method.
* Create a function to filter out dataset examples where the English sentence is greater than or equal to than 13 (embedded) tokens in length. Apply this function to both Dataset objects using the filter method.
* Create a function to map over the datasets that pads each English sequence of embeddings with some distinct padding value before the sequence, so that each sequence is length 13. Apply this function to both Dataset objects using the map method. _Hint: look at the tf.pad function. You can extract a Tensor shape using tf.shape; you might also find the tf.math.maximum function useful._
* Batch both training and validation Datasets with a batch size of 16.
* Print the `element_spec` property for the training and validation Datasets. 
* Using the Dataset `.take(1)` method, print the shape of the English data example from the training Dataset.
* Using the Dataset `.take(1)` method, print the German data example Tensor from the validation Dataset.
"""

import numpy as np
eng_2=np.array(eng)

from sklearn.model_selection import train_test_split
Xtrain,Xtest,ytrain,ytest = train_test_split(germ_final,eng,test_size=0.2)

train_data = tf.data.Dataset.from_tensor_slices((Xtrain,ytrain))
val_data = tf.data.Dataset.from_tensor_slices((Xtest,ytest))
print(train_data.element_spec)
print(val_data.element_spec)

def map_1(germ,eng):
  eng = tf.strings.split(eng,sep=" ")
  
  return (germ,eng)

train_data1 = train_data.map(map_1)
val_data1 = val_data.map(map_1)

def get_new(dataset):
  new_x1=[]
  new_y1=[]
  for x,y in dataset:
    y=embedding_layer(y)
    if y.shape[0]>=13:
      shape=0
    else:
      shape=y.shape[0]
    paddings=tf.constant([[13-shape,0],[0,0]])
    y=tf.pad(y,paddings,"CONSTANT")
    new_x1.append(x)
    new_y1.append(y)
  new_x1=np.array(new_x1)
  new_y1=np.array(new_y1)
  return new_x1,new_y1

new_x,new_y=get_new(train_data1)
new_x1,new_y1=get_new(val_data1)

print(new_x.shape,new_y.shape)

dataset_1_train= tf.data.Dataset.from_tensor_slices((new_x,new_y))
print(dataset_1_train.element_spec)

dataset_1_test = tf.data.Dataset.from_tensor_slices((new_x1,new_y1))

dataset_1_train=dataset_1_train.batch(16,drop_remainder=True)
dataset_1_test=dataset_1_test.batch(16,drop_remainder=True)
print(dataset_1_train.element_spec)
print(dataset_1_test.element_spec)

for x,y in dataset_1_train.take(1):
  print(x,y)
for x,y in dataset_1_test.take(1):
  print(x,y)

"""## 3. Create the custom layer
You will now create a custom layer to add the learned end token embedding to the encoder model:
"""

# Run this cell to download and view a schematic diagram for the encoder model

!wget -q -O neural_translation_model.png --no-check-certificate "https://docs.google.com/uc?export=download&id=1JrtNOzUJDaOWrK4C-xv-4wUuZaI12sQI"
Image("neural_translation_model.png")

"""You should now build the custom layer.
* Using layer subclassing, create a custom layer that takes a batch of English data examples from one of the Datasets, and adds a learned embedded ‘end’ token to the end of each sequence. 
* This layer should create a TensorFlow Variable (that will be learned during training) that is 128-dimensional (the size of the embedding space). _Hint: you may find it helpful in the call method to use the tf.tile function to replicate the end token embedding across every element in the batch._
* Using the Dataset `.take(1)` method, extract a batch of English data examples from the training Dataset and print the shape. Test the custom layer by calling the layer on the English data batch Tensor and print the resulting Tensor shape (the layer should increase the sequence length by one).
"""

embedding_layer(tf.constant(["end"])).shape

print(len(word_index.keys()))

class CustomLayer(tf.keras.layers.Layer):

  def __init__(self,*args,**kwargs):
    super(CustomLayer,self).__init__(*args,**kwargs)
    
    
    self.w = tf.Variable(tf.random_uniform_initializer(0., 1.)(shape=(1, 1, 128)))
    #self.w= tf.tile(self.w,tf.constant([input_shape[0],1,1]))
    
  def call(self,inputs):
    tiling = tf.tile(self.w, [tf.shape(inputs)[0], 1, 1])
    return tf.concat((inputs,tiling),axis=1)

layer = CustomLayer()
for x,y in dataset_1_train.take(1):
  print(layer(y).shape)



"""## 4. Build the encoder network
The encoder network follows the schematic diagram above. You should now build the RNN encoder model.
* Using the functional API, build the encoder network according to the following spec:
    * The model will take a batch of sequences of embedded English words as input, as given by the Dataset objects.
    * The next layer in the encoder will be the custom layer you created previously, to add a learned end token embedding to the end of the English sequence.
    * This is followed by a Masking layer, with the `mask_value` set to the distinct padding value you used when you padded the English sequences with the Dataset preprocessing above.
    * The final layer is an LSTM layer with 512 units, which also returns the hidden and cell states.
    * The encoder is a multi-output model. There should be two output Tensors of this model: the hidden state and cell states of the LSTM layer. The output of the LSTM layer is unused.
* Using the Dataset `.take(1)` method, extract a batch of English data examples from the training Dataset and test the encoder model by calling it on the English data Tensor, and print the shape of the resulting Tensor outputs.
* Print the model summary for the encoder network.
"""

input_layer = tf.keras.layers.Input((13, 128))
x=CustomLayer()(input_layer)
x=tf.keras.layers.Masking(mask_value=0)(x)
x,hidden_state,cell_state=tf.keras.layers.LSTM(512,return_state=True)(x)

model =tf.keras.models.Model(inputs=input_layer,outputs=[hidden_state,cell_state])
print(model.summary())

for x,y in dataset_1_train.take(1):
  hidden_states,cell_states=model(y)
  print(hidden_states.shape,cell_states.shape)

"""## 5. Build the decoder network
The decoder network follows the schematic diagram below. 
"""

# Run this cell to download and view a schematic diagram for the decoder model

!wget -q -O neural_translation_model.png --no-check-certificate "https://docs.google.com/uc?export=download&id=1DTeaXD8tA8RjkpVrB2mr9csSBOY4LQiW"
Image("neural_translation_model.png")

"""You should now build the RNN decoder model.
* Using Model subclassing, build the decoder network according to the following spec:
    * The initializer should create the following layers:
        * An Embedding layer with vocabulary size set to the number of unique German tokens, embedding dimension 128, and set to mask zero values in the input.
        * An LSTM layer with 512 units, that returns its hidden and cell states, and also returns sequences.
        * A Dense layer with number of units equal to the number of unique German tokens, and no activation function.
    * The call method should include the usual `inputs` argument, as well as the additional keyword arguments `hidden_state` and `cell_state`. The default value for these keyword arguments should be `None`.
    * The call method should pass the inputs through the Embedding layer, and then through the LSTM layer. If the `hidden_state` and `cell_state` arguments are provided, these should be used for the initial state of the LSTM layer. _Hint: use the_ `initial_state` _keyword argument when calling the LSTM layer on its input._
    * The call method should pass the LSTM output sequence through the Dense layer, and return the resulting Tensor, along with the hidden and cell states of the LSTM layer.
* Using the Dataset `.take(1)` method, extract a batch of English and German data examples from the training Dataset. Test the decoder model by first calling the encoder model on the English data Tensor to get the hidden and cell states, and then call the decoder model on the German data Tensor and hidden and cell states, and print the shape of the resulting decoder Tensor outputs.
* Print the model summary for the decoder network.
"""

unique_tokens= len(word_index.keys())+1
class MyModel(tf.keras.models.Model):

  def __init__(self,**kwargs):
    super(MyModel,self).__init__(**kwargs)
    self.embd=tf.keras.layers.Embedding(input_dim=unique_tokens,output_dim=128,mask_zero=True)
    self.lstm = tf.keras.layers.LSTM(512,return_sequences=True,return_state=True)
    self.dense = tf.keras.layers.Dense(units =unique_tokens)

  def call(self,inputs,hidden_state=None,cell_state=None):
    if hidden_state is not None:
      assert cell_state is not None
      encoder_states=[hidden_state,cell_state]
    else:
      encoder_states=None

    emb = self.embd(inputs)
    x,stateh,statec = self.lstm(emb,initial_state=encoder_states)
    out=self.dense(x)

    return out,stateh,statec


model2 =MyModel()

for x, y in dataset_1_train.take(1):
  hidden,cell = model(y)
  out,hidden1,cell1=model2(x,hidden,cell)
  print(out.shape,hidden1.shape,cell1.shape)

print(model2.summary())

"""## 6. Make a custom training loop
You should now write a custom training loop to train your custom neural translation model.
* Define a function that takes a Tensor batch of German data (as extracted from the training Dataset), and returns a tuple containing German inputs and outputs for the decoder model (refer to schematic diagram above).
* Define a function that computes the forward and backward pass for your translation model. This function should take an English input, German input and German output as arguments, and should do the following:
    * Pass the English input into the encoder, to get the hidden and cell states of the encoder LSTM.
    * These hidden and cell states are then passed into the decoder, along with the German inputs, which returns a sequence of outputs (the hidden and cell state outputs of the decoder LSTM are unused in this function).
    * The loss should then be computed between the decoder outputs and the German output function argument.
    * The function returns the loss and gradients with respect to the encoder and decoder’s trainable variables.
    * Decorate the function with `@tf.function`
* Define and run a custom training loop for a number of epochs (for you to choose) that does the following:
    * Iterates through the training dataset, and creates decoder inputs and outputs from the German sequences.
    * Updates the parameters of the translation model using the gradients of the function above and an optimizer object.
    * Every epoch, compute the validation loss on a number of batches from the validation and save the epoch training and validation losses.
* Plot the learning curves for loss vs epoch for both training and validation sets.

_Hint: This model is computationally demanding to train. The quality of the model or length of training is not a factor in the grading rubric. However, to obtain a better model we recommend using the GPU accelerator hardware on Colab._
"""

print(dataset_1_train.element_spec)

def create_input_output(data):
  inputs = tf.pad(tf.slice(data,[0,1],[-1,-1]),tf.constant([[0, 0,], [0, 1]]))
  otputs = tf.reshape(data[data!=2],[data.shape[0],-1])
  return inputs , tf.pad(otputs,tf.constant([[0, 0,], [0, 1]]))

for x,y in dataset_1_train.take(1):
  print(x.shape)
  inp,out = create_input_output(x)
  print(inp.shape,out.shape)
  #print(x==inp)

@tf.function
def forw_back_pass(eng,germ_in,germ_out):
    with tf.GradientTape() as tape:
      hidden,cell = model(eng)
      out,hidden_1,cell1=model2(germ_in,hidden,cell)
      loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)(germ_out,out)
      grad = tape.gradient(loss,model.trainable_variables+model2.trainable_variables)
    return loss,grad

optimizer=tf.keras.optimizers.Adam()
train_loss=[]
val_loss=[]
for epoch in range(20):
  epoch_train_loss=tf.keras.metrics.Mean()
  epoch_val_loss = tf.keras.metrics.Mean()
  for x,y in dataset_1_train:
    x_in,x_out=create_input_output(x)
    loss,grad=forw_back_pass(y,x_in,x_out)
    optimizer.apply_gradients(zip(grad,model.trainable_variables+model2.trainable_variables))
    epoch_train_loss(loss)
  for x1,y1 in dataset_1_test:
    x1_in,x1_out=create_input_output(x1)
    loss1,_=forw_back_pass(y1,x1_in,x1_out)
    epoch_val_loss(loss1)
  print(f"train loss: {epoch_train_loss.result()}, val_loss: {epoch_val_loss.result()}")
  train_loss.append(epoch_train_loss.result())
  val_loss.append(epoch_val_loss.result())

model.save_weights("gdrive/MyDrive/model/checkpoint")
model2.save_weights("gdrive/MyDrive/model/checkpoint1")

import matplotlib.pyplot as plt
plt.plot(range(0,20),train_loss)
plt.plot(range(0,20),val_loss)
plt.legend(("train_loss","val_loss"))
plt.show()

"""## 7. Use the model to translate
Now it's time to put your model into practice! You should run your translation for five randomly sampled English sentences from the dataset. For each sentence, the process is as follows:
* Preprocess and embed the English sentence according to the model requirements.
* Pass the embedded sentence through the encoder to get the encoder hidden and cell states.
* Starting with the special  `"<start>"` token, use this token and the final encoder hidden and cell states to get the one-step prediction from the decoder, as well as the decoder’s updated hidden and cell states.
* Create a loop to get the next step prediction and updated hidden and cell states from the decoder, using the most recent hidden and cell states. Terminate the loop when the `"<end>"` token is emitted, or when the sentence has reached a maximum length.
* Decode the output token sequence into German text and print the English text and the model's German translation.
"""

def preprocess_eng_sent(eng_test_sent):
  eng_test_sent = tf.strings.split(eng_test_sent)
  eng_test_sent_embd = embedding_layer(eng_test_sent)
  paddings = tf.constant([[13 - eng_test_sent.shape[0], 0,], [0, 0]]) 
  eng_test_sent_embd_padd = tf.pad(eng_test_sent_embd,paddings) 
  print('prepeocessed data[embedded] shape:', eng_test_sent_embd_padd.shape) 
  return eng_test_sent_embd_padd

def process_eng_embeddings(eng_embd):
# Pass the embedded sentence through the encoder to get the encoder hidden and cell states.
  hidden_state, cell_state = model(tf.expand_dims(eng_embd,0))
  # Starting with the special "<start>" token, use this token and the final encoder h idden and cell states
  # to get the one-step prediction from the decoder, as well as the decoder’s updated hidden and cell states.
  start_seq = tf.constant([[ 1]])
  decoder_out,hidden_state,cell_state=model2(start_seq,hidden_state,cell_state)
  #print(np.argmax(decoder_out.numpy(),axis=2))
  next_seq = start_seq 
  for i in range(12):
    decoder_out , hidden_state, cell_state = model2(next_seq,hidden_state, cell_state)
    decoder_out_decoded = np.argmax(decoder_out.numpy(),axis=2) #print('one step out :' ,decoder_out_decoded[0][0])
    next_seq = np.append(next_seq,[[decoder_out_decoded[0][0]]],axis=1)
    if 2 in next_seq: 
      break
  return next_seq

tocken_dict = word_index
rev_tocken_dict = {v:k for k,v in tocken_dict.items() }
def ger_tocken_to_sentence(seqence): 
  german_out = ''
  for i in seqence[0]:
    if i!=0:
      german_out = german_out + ' '+(rev_tocken_dict[i]) 
  german_out = german_out.replace('<start>','').replace('<end>','')
  return german_out

for index in np.random.choice(NUM_EXAMPLES,5):
  eng_sent_embedding = preprocess_eng_sent(eng[index]) 
  output_sequence = process_eng_embeddings(eng_sent_embedding) #print(output_sequence)
  german_out_sentence = ger_tocken_to_sentence(output_sequence)
  print('input english sentence: ', eng[index]) 
  print('output german sentence: ', german_out_sentence) 
  print('\n')

print(ytest[0])

